version: "3.7"

services:
  web:
    image: webdevops/php-apache:alpine-php7
    ports:
      - "80:80"
    volumes:
      - .\data\php\:/app

    networks:
      - rede

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "formulario"
      MYSQL_DATABASE: "contato"
    ports:
      - "3306:3306"
    volumes:
      - .\data\mysql\:/var/lib/mysql

    networks:
      - rede

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: "formulario"
    ports:
      - "8080:80"

    networks:
      - rede

networks:
   rede:
     driver: bridge